language: node_js

node_js:
- "node"

notifications:
  email:
    recipients:
      - tates001@gmail.com
    on_success: always
    on_failure: always

deploy:
  provider: npm
  email: tates001@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    branch: master